<?php require_once getcwd() . '/../../xhprof_lib/utils/common.php'; ?>
<?php // echo get_home_button(); ?>
<div class="container">
    <div class="dash-header">
        <div class="xh-title-wrap">
            <a class="xh-title" href="<?php print get_home_url(); ?>">XH GUI</a>
        </div>

        <div id="options">
            <form name="simple_bar" method="get" action="">
                <label id="engine">
                    Engine:
                    <select>
                        <option>circo</option>
                        <option selected>dot</option>
                        <option>fdp</option>
                        <option>neato</option>
                        <option>osage</option>
                        <option>twopi</option>
                    </select>
                </label>

                <label id="format">
                    Format:
                    <select>
                        <option selected>svg</option>
                        <option>png</option>
                        <option>xdot</option>
                        <option>plain</option>
                        <option>ps</option>
                    </select>
                </label>

                <label id="raw">
                    <input type="checkbox"> Show raw output
                </label>

                <?php echo get_show_internal_button('Show internal functions', 1); ?>
                <span class="threshold">Threshold
                    <?php
                    echo get_threshold_button('++', 0.1, $threshold);
                    echo get_threshold_button('+', 0.01, $threshold);
                    echo get_threshold_button('-', -0.01, $threshold);
                    echo get_threshold_button('--', -0.1, $threshold);
                    ?>
                </span>
            </form>
        </div>
    </div>
</div>