version: '3'
services:

  php:
    build:
      context: ./
      dockerfile: php/Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}_php"
    environment:
      SITE_URL: "http://${PROJECT_BASE_URL}:${PROJECT_PORT}"
    networks:
      - local
    volumes:
      - ../:/var/www/xhprof
      - ./database:/database:cached
      - ./traces:/traces

  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}_nginx"
    depends_on:
      - php
    ports:
      - "${PROJECT_PORT}:80"
    volumes:
      - ../:/var/www/xhprof
    networks:
      - local

  mariadb:
    image: wodby/mariadb:latest
    container_name: "${COMPOSE_PROJECT_NAME}_db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_PORT: "${DB_PORT}"
      MYSQL_INNODB_BUFFER_POOL_SIZE: 5G
      MYSQL_NET_READ_TIMEOUT: 360
      MYSQL_NET_WRITE_TIMEOUT: 360
    networks:
      - local
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "43306:3306"

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}_pma"
    restart: always
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: "${DB_PORT}"
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASS}"
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
      PMA_ARBITRARY: 1
    networks:
      - local
    ports:
      - "8001:80"

volumes:
  dbdata:

networks:
  local:
